from telegram.ext import ConversationHandler

# User Registration States
START = 0
CHOOSE_ROLE = 1
SET_LOCATION = 2

# Seller States
ADD_PRODUCT = 10
SET_PRODUCT_NAME = 11
SET_PRODUCT_PRICE = 12
SET_PRODUCT_DESCRIPTION = 13
SET_PRODUCT_IMAGE = 14
SET_PRODUCT_LOCATION = 15

# Buyer States
BROWSE_PRODUCTS = 20
SELECT_PRODUCT = 21
SET_QUANTITY = 22
CONFIRM_ORDER = 23
CHOOSE_PAYMENT = 24
PROCESS_PAYMENT = 25
TRACK_ORDER = 26

# Head Admin States
MANAGE_SELLERS = 30
ADD_ADDRESSES = 31
MANAGE_USERS = 32
VIEW_REPORTS = 33

# Payment States
PAYMENT_METHOD_SELECT = 40
CRYPTO_PAYMENT = 41
CARD_PAYMENT = 42
PAYMENT_CONFIRMATION = 43
PAYMENT_VERIFICATION = 44

# Error States
ERROR_HANDLING = 90
SESSION_EXPIRED = 91
MAINTENANCE_MODE = 92

# Security States
VERIFICATION = 95
BLOCKING = 96
TIMEOUT = 97

# Common States
CANCEL = 99
